version: "3"
services: 
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 4000:3000
    volumes: 
      - ./src:/app/src
    container_name: react-container
    image: react-image-0
    env_file: 
      - ./.env
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

    
